# -*- mode: python; -*-

Import("env")

env = env.Clone()

env.Library(
    target='timeseries_options',
    source=[
        'timeseries_options.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
    ],
)

env.Library(
    target='timeseries_namespace',
    source=[
        'timeseries_namespace.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/catalog/database',
        '$BUILD_DIR/mongo/db/db_raii',
        '$BUILD_DIR/mongo/db/namespace_string',
        '$BUILD_DIR/mongo/db/storage/write_unit_of_work',
    ],
)

env.Library(
    target='bucket_catalog',
    source=[
        'bucket_catalog.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/namespace_string',
    ],
)

env.Library(
    target='insert_router',
    source=[
        'insert_router.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        '$BUILD_DIR/mongo/db/repl/oplog',
        'bucket_catalog',
    ],
)

env.Library(
    target='query_translator',
    source=[
        'query_translator.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        '$BUILD_DIR/mongo/db/pipeline/aggregation_request',
    ],
)

env.CppUnitTest(
    target='query_translator_test',
    source=[
        'query_translator_test.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/db/catalog/collection_options',
        'query_translator',
    ],
)
